# Generated by Django 6.0.6 on 2026-06-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('w', 'Waiter'), ('b', 'Billing'), ('k', 'Kitchen'), ('o', 'Owner')], max_length=2),
        ),
    ]
