# Generated by Django 6.0.6 on 2026-06-21 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0003_alter_catagory_options_alter_menuitem_price_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='OrderApp.order'),
            preserve_default=False,
        ),
    ]
