# Generated by Django 6.0.6 on 2026-06-22 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0005_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('p', 'Preparing'), ('r', 'Ready'), ('s', 'Served'), ('b', 'Billed')])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='OrderApp.order')),
            ],
        ),
    ]
