# Generated by Django 6.0.6 on 2026-06-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0006_orderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('p', 'Preparing'), ('r', 'Ready'), ('s', 'Served')], default='p', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('p', 'Preparing'), ('ps', 'Partially Served'), ('s', 'Served'), ('b', 'Billed')], default='p', max_length=2),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(choices=[('p', 'Preparing'), ('ps', 'Partially Served'), ('s', 'Served'), ('b', 'Billed')]),
        ),
    ]
