# Generated by Django 6.0.6 on 2026-06-25 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0007_orderitem_status_alter_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KITCHEN_STATION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='default_priority',
            field=models.CharField(choices=[('3', 'High'), ('2', 'Medium'), ('1', 'Low')], default='2', max_length=2),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='est_time',
            field=models.PositiveIntegerField(blank=True, help_text='Write estimated time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='priority',
            field=models.CharField(choices=[('3', 'High'), ('2', 'Medium'), ('1', 'Low')], default='2', max_length=2),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderApp.kitchen_station'),
        ),
    ]
