# Generated by Django 6.0.6 on 2026-06-26 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0008_kitchen_station_menuitem_default_priority_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KITCHEN_STATION',
            new_name='KitchenStation',
        ),
    ]
