# Generated by Django 6.0.6 on 2026-06-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0010_kitchenstation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenstation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
